<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240925164336 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE course (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_169E6FB9FE54D947 ON course (group_id)');
        $this->addSql('CREATE TABLE "group" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE lesson (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, level INT NOT NULL, unit_id BIGINT DEFAULT NULL, course_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F87474F3F8BD700D ON lesson (unit_id)');
        $this->addSql('CREATE INDEX IDX_F87474F3591CC992 ON lesson (course_id)');
        $this->addSql('CREATE TABLE lesson_task (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, lesson_id BIGINT NOT NULL, task_id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6B0F1D41CDF80196 ON lesson_task (lesson_id)');
        $this->addSql('CREATE INDEX IDX_6B0F1D418DB60186 ON lesson_task (task_id)');
        $this->addSql('CREATE TABLE task (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE unit (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, level INT NOT NULL, course_id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DCBB0C53591CC992 ON unit (course_id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F3F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F3591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson_task ADD CONSTRAINT FK_6B0F1D41CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson_task ADD CONSTRAINT FK_6B0F1D418DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE course DROP CONSTRAINT FK_169E6FB9FE54D947');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_F87474F3F8BD700D');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_F87474F3591CC992');
        $this->addSql('ALTER TABLE lesson_task DROP CONSTRAINT FK_6B0F1D41CDF80196');
        $this->addSql('ALTER TABLE lesson_task DROP CONSTRAINT FK_6B0F1D418DB60186');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C53591CC992');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE lesson');
        $this->addSql('DROP TABLE lesson_task');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE unit');
    }
}
